### ISSUE TITLE
No version released in ansible galaxy

### ISSUE THREAD

**Issue by selvakn** [dochang/ansible-role-docker#10]
If released, will be helpful for installation using `ansible-galaxy`

**Comment by dochang** [comment]
Do you want a "stable" version? Isn't a "master" snapshot enough?

**Comment by selvakn** [comment]
Yeah. For example, freezing to a particular version.

**Comment by dochang** [comment]
OK!

https://github.com/dochang/ansible-role-docker/releases/tag/1.0.0

Enjoy it!
