### ISSUE TITLE
Ansible 1.9.4 regex_escape error

### ISSUE THREAD

**Issue by stephenrlouie** [dochang/ansible-role-docker#11]
- Ansible Galaxy states the [min ansible version](https://galaxy.ansible.com/dochang/docker/) is 1.8 but I'm seeing errors on 1.9.4
- Is there a quick fix to this, I see that regex_escape was added in [2.0](http://docs.ansible.com/ansible/playbooks_filters.html)

Here is the output I'm seeing.

```
TASK: [docker | replace source uri in the script] ***************************** 
fatal: [gem-master01] => Failed to template {{ "https://apt.dockerproject.org" | regex_escape }}: template error while templating string: no filter named 'regex_escape'

FATAL: all hosts have already failed -- aborting
```

**Comment by dochang** [comment]
`regex_escape` is required for replacing the repo urls.  I will update `min_ansible_version` to `2.0`.

Instead of staying on 1.9.x, I suggest that you better upgrade Ansible.

**Comment by stephenrlouie** [comment]
Ah unfortunately my project has to for now due to some bugs in 2.0 that 
 will break the project.

**Comment by dochang** [comment]
You can try this: edit Ansible code to add `regex_escape`, then run the modified version locally.

https://github.com/ansible/ansible/tree/v1.9.4-1/lib/ansible/runner/filter_plugins

**Comment by stephenrlouie** [comment]
@dochang Would you have any interest in supporting a pre 2.0 release? Given there are projects who are stuck on pre 2.0 due to production requirements like us for the [gemini-project](https://github.com/gemini-project). I'd be up for contributing to this or would at least appreciate any guidance / opinions on supporting pre 2.0 ansible distributions. 

Could also implement a similar role upstream in the kubernetes community [here](https://github.com/kubernetes/contrib/tree/master/ansible/roles/docker).   

You can see the path of least resistance [work-around](https://github.com/gemini-project/gemini-ansible/pull/63) I have right now

CC @danehans

**Comment by dochang** [comment]
@stephenrlouie Could you try to put this custom [plugin](https://gist.github.com/dochang/6125f855c4f52e75f62243a71d414730) in the `filter_plugins` directory in the top dir of the playbooks?  I try to put the plugin in the role but it doesn't work.  Ansible 1 requires the plugins in the playbooks directory.

I've tested and ensure the filter works in my local playbook directory with Ansible 1.9.4 .

If this solution still doesn't work, I'll release a 1.9.x fork.

**Comment by stephenrlouie** [comment]
Thanks @dochang - I'll let you know towards the end of this week.

**Comment by stephenrlouie** [comment]
@dochang it works! 

Thanks for making that filter plugin, feel free to refer to https://github.com/gemini-project/gemini-ansible/pull/64 as an example use of your role with ansible < 2.0
