### ISSUE TITLE
autoinstall pip as dependency?

### ISSUE THREAD

**Issue by Name63** [dochang/ansible-role-docker#12]
When running on a fresh system without pip

> TASK [dochang.docker : install docker-py] **************************************
> fatal: [192.168.56.101]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to find required executable pip"}

**Comment by dochang** [comment]
You can install pip by other roles/playbooks.  For example https://galaxy.ansible.com/dochang/pip/.

There're many pip roles. You can find them on Ansible Galaxy & Github.
