### ISSUE TITLE
Possible to pin version of docker that is installed?

### ISSUE THREAD

**Issue by JONBRWN** [dochang/ansible-role-docker#15]
Ran into this problem today https://github.com/docker/for-linux/issues/11 due to the fact that this role installs the latest version of Docker.

Is it currently possible to pin to a particular version when using this role?

Thanks

**Comment by dochang** [comment]
Currently this role depends on the official install script from <https://get.docker.com> and the script just installs the latest version of Docker.  So we're unable to pin the version in this role.

But there're other ways to achieve it.  You can use the pinning mechanism of your OS package manager.

For APT:

  - https://wiki.debian.org/AptPreferences#Pinning-1
  - https://manpages.debian.org/stretch/apt/apt_preferences.5.en.html
  - https://www.debian.org/doc/manuals/debian-reference/ch02.en.html#_tweaking_candidate_version

For YUM:

  - https://access.redhat.com/solutions/98873

For instance, on an APT-based system, try to put the following configuration in `/etc/apt/preferences.d/50-docker`:

```
Package: <YOUR PACKAGE>
Pin: version <VERSION>
Pin-Priority: 900
```

**Comment by JONBRWN** [comment]
thanks, I'll look into options outside of this role to do the pinning.
